#!/bin/bash
set -e; 

# Check if name is specified
if [[ $1 == postgresql:* ]]; then
    if [ -z $2 ] && [ $1 != postgresql:list ]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
    if [[ ! -d "$PLUGIN_PATH/link" ]]; then
        echo "Link plugin not found... Did you install it from https://github.com/rlaneve/dokku-link?"
        exit 1
    fi
    PLUGIN_NAME="postgresql"
    PLUGIN_ALIAS="db"
    CONTAINER_NAME="${PLUGIN_NAME}_${APP}"
    HOST_DIR="$DOKKU_ROOT/.$PLUGIN_NAME/$APP"
    CONTAINER_IMAGE="jlachowski/postgresql"
    DB_PORT=5432
fi

case "$1" in

  postgresql:create)
    # Check if Rabbitmq container is installed
    IMAGE=$(docker images | grep "$CONTAINER_IMAGE" |  awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi
    if [[ ! -d "$HOST_DIR" ]]; then
        mkdir -p "$HOST_DIR"
    fi
    # Check if an existing storage volume exists
    if [[ -d "$HOST_DIR/volume" ]]; then
        echo
        echo "-----> Reusing $PLUGIN_NAME/$APP storage"
    else
        mkdir -p "$HOST_DIR/volume"
        # Generate random password for users
        DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
        echo $DB_PASSWORD > "$HOST_DIR/pwd-$APP"
        chown -R dokku:dokku "$HOST_DIR"
        chmod 700 "$HOST_DIR/pwd-$APP"
    fi
    VOLUME="$HOST_DIR/volume:/opt/postgresql"
    # Stop existing container with the same persistent Rabbitmq
    ID=$(docker ps | grep "$CONTAINER_NAME" |  awk '{print $1}')
    if [[ ! -z "$ID" ]]; then
        docker stop $ID > /dev/null
    fi
    # Launch container
    ID=$(docker run -v $VOLUME -name=$CONTAINER_NAME -d $CONTAINER_IMAGE /usr/bin/start-pgsql.sh $DB_PASSWORD)
    sleep 1
    # Link to a potential existing app
    dokku postgresql:link $APP $APP
    echo
    echo "-----> PostgreSQL container created: $CONTAINER_NAME (using $CONTAINER_IMAGE)"
    sleep 1
    dokku postgresql:info $APP
    ;;
  
  postgresql:clone)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a name for the clone"
            exit 1
        fi
        TARGET_DIR="$DOKKU_ROOT/.$PLUGIN_NAME/$3"
        if [[ -d "$TARGET_DIR" ]]; then
            echo "Persistent storage for ${PLUGIN_NAME}_$3 already exists"
            exit 1
        fi
        echo
        echo "-----> Cloning $PLUGIN_NAME/$APP storage"
        cp -r "$HOST_DIR" "$TARGET_DIR"

        # Create new container with copied storage
        dokku postgresql:create $3
    fi
    ;;

  postgresql:delete)
    echo
    echo "-----> This will permanently remove all the stored data. Are you sure (yes/no)?"
    read ANSWER
    if [[ $ANSWER == "yes" ]]; then
        # Stop the container
        ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
        if [[ ! -z $ID ]]; then
            docker stop $ID > /dev/null
            docker rm $ID > /dev/null
        fi

        dokku link:delete "$APP" "$CONTAINER_NAME" "$PLUGIN_ALIAS"
        dokku config:unset "$APP" "DB_SCHEME" "DB_USERNAME" "DB_PASSWORD" "DB_PATH"

        # Remove persistent volume
        if [[ -d "$HOST_DIR" ]]; then
            rm -rf "$HOST_DIR"
        fi
        echo
        echo "-----> PostgreSQL container deleted: $CONTAINER_NAME"
    fi
    ;;

  postgresql:info)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
    DOCKER_GATEWAY=$(docker inspect $ID | grep Gateway | awk '{ print $2 }' | tr -d ',"')
    echo
    echo "       Host: $IP"
    echo "       Gateway: $DOCKER_GATEWAY"
    echo "       Secret port: $DB_PORT"
    echo
    ;;

  postgresql:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a container name"
            exit 1
        fi
        CONTAINER_NAME="${PLUGIN_NAME}_$3"
        if [[ ! -f "$HOST_DIR/pwd-$3" ]]; then
            echo "Postgresql is not correctly initialized"
            exit 0
        fi
        ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
        #IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
        DB_PASSWORD=$(cat "$HOST_DIR/pwd-$3")

        dokku link:create "$APP" "$CONTAINER_NAME" "$PLUGIN_ALIAS"
        # Write BROKER_URL to app's ENV file using dokku command
        dokku config:set $APP "DB_SCHEME=postgresql" "DB_USERNAME=root" "DB_PASSWORD=$DB_PASSWORD" "DB_PATH=/db"
        echo
        echo "-----> $APP linked to $CONTAINER_NAME container"
    fi
    ;;

  postgresql:logs)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  postgresql:list)
    CONTAINERS=$(ls -1 "$DOKKU_ROOT/.$PLUGIN_NAME/" | awk '{print $1}')
    echo "PostgreSQL containers:"
    for CONTAINER in $CONTAINERS; do
        echo "  - $CONTAINER"
    done
    ;;

  help)
    cat && cat<<EOF
    postgresql:create <app>           Create a PostgreSQL container for <app>
    postgresql:clone <app> <trg>      Clone PostgreSQL container of <app> for <trg>
    postgresql:delete <app>           Delete specified PostgreSQL container for <app>
    postgresql:info <app>             Display <app> PostgreSQL container informations
    postgresql:link <app> <pgsql>     Link an app to a PostgreSQL container
    postgresql:list                   Display list of PostgreSQL containers
    postgresql:logs <app>             Display last logs from <app> PostgreSQL container
EOF
    ;;

esac
