#!/bin/bash

# Build docker image
git clone https://github.com/jlachowski/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t jlachowski/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles
