#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

APP="$1"
PLUGIN_FLAG_PERSISTENCE_FILE="$DOKKU_ROOT/$APP/PROGRESQL"
CONTAINER_NAME="progresql-$APP"

# Only start Postgresql if it is enabled
if [[ -f $PLUGIN_FLAG_PERSISTENCE_FILE ]]; then
	dokku_log_info1 "Preparing Postgresql for $APP..."

  # Link to app
  dokku link:create $APP $CONTAINER_NAME db
  dokku_log_info1 "Postgresql container linked: $APP -> $CONTAINER_NAME"
fi
