#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail
# Fail on equation failure
set -e

APP="$1"
PLUGIN_FLAG_PERSISTENCE_FILE="$DOKKU_ROOT/$APP/POSTGRESQL"
CONTAINER_NAME="postgresql-$APP"

dokku link:delete "$APP" "CONTAINER_NAME" db
