#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set +exo pipefail

source "$(dirname $0)/defaults"

APP="$1"
PLUGIN_FLAG_PERSISTANCE_FILE="$DOKKU_ROOT/$APP/$PERSISTANCE_FILE"
CONTAINER_NAME="${PLUGIN_NAME}-${APP}"

dokku link:delete "$APP" "$CONTAINER_NAME" "$PLUGIN_ALIAS"
