#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
dokku_log_info1 "1 - Preparing Postgresql for $APP..."
# Reset bash mode from importing the functions
set +exo pipefail
dokku_log_info1 "2 - Preparing Postgresql for $APP..."

source "$(dirname $0)/defaults"

APP="$1"
PLUGIN_FLAG_PERSISTANCE_FILE="$DOKKU_ROOT/$APP/$PERSISTANCE_FILE"
CONTAINER_NAME="${PLUGIN_NAME}-${APP}"

# Only start Postgresql if it is enabled
if [[ -f $PLUGIN_FLAG_PERSISTENCE_FILE ]]; then
  dokku_log_info1 "Preparing Postgresql for $APP..."

  # Link to app
  dokku link:create "$APP" "$CONTAINER_NAME" "$PLUGIN_ALIAS""
  dokku_log_info1 "Postgresql container linked: $APP -> $CONTAINER_NAME"
fi
