#!/usr/bin/env bash
source "$(dirname $0)/../common/functions"
# Reset bash mode from importing the functions
set -o pipefail; [[ $DOKKU_TRACE ]] && set -x
set +e

source "$(dirname $0)/defaults"

APP="$1"
CONTAINER_NAME="${PLUGIN_NAME}-${APP}"

dokku link:delete "$APP" "$CONTAINER_NAME" "$PLUGIN_ALIAS"
